#!/bin/bash

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Log functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    log_error "Please run as root"
    exit 1
fi

# Default values
INSTALL_DIR="/opt/password-vault"
CONFIG_DIR="/etc/password-vault"
LOG_DIR="/var/log/password-vault"
DATA_DIR="/var/lib/password-vault"
SERVICE_USER="password-vault"
SERVICE_GROUP="password-vault"
PYTHON_VENV="${INSTALL_DIR}/venv"
DB_NAME="password_vault"
DB_USER="password_vault"
DB_PASS="$(openssl rand -hex 16)"  # Generate random password

# Create required directories
create_directories() {
    log_info "Creating directory structure..."
    mkdir -p "${INSTALL_DIR}"
    mkdir -p "${CONFIG_DIR}"
    mkdir -p "${LOG_DIR}"
    mkdir -p "${DATA_DIR}"
    mkdir -p "${DATA_DIR}/db"
}

# Create service user and group
create_service_user() {
    log_info "Creating service user and group..."
    if ! getent group "${SERVICE_GROUP}" >/dev/null; then
        groupadd -r "${SERVICE_GROUP}"
    fi
    if ! getent passwd "${SERVICE_USER}" >/dev/null; then
        useradd -r -g "${SERVICE_GROUP}" -d "${INSTALL_DIR}" -s /sbin/nologin "${SERVICE_USER}"
    fi
}

# Install Python dependencies
install_python_deps() {
    log_info "Installing Python dependencies..."
    # RHEL-specific Python package requirements
    dnf install -y python39 python39-devel postgresql-devel gcc

    # Create and activate virtual environment
    python3.9 -m venv "${PYTHON_VENV}"
    source "${PYTHON_VENV}/bin/activate"
    
    # Upgrade pip and install requirements
    pip install --upgrade pip
    pip install -r requirements.txt
}

# Configure PostgreSQL
setup_database() {
    log_info "Setting up PostgreSQL..."
    
    # Install PostgreSQL if not present
    if ! rpm -q postgresql-server >/dev/null; then
        dnf install -y postgresql-server postgresql-contrib
        postgresql-setup --initdb
    fi

    # Configure pg_hba.conf for password authentication
    PG_HBA_FILE="/var/lib/pgsql/data/pg_hba.conf"
    cp "${PG_HBA_FILE}" "${PG_HBA_FILE}.bak"
    cat > "${PG_HBA_FILE}" << EOF
# Generated by password-vault installer
local   all             all                                     md5
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
EOF

    # Start PostgreSQL if not running
    systemctl enable postgresql
    systemctl start postgresql

    # Create database and user
    echo "Creating database and user..."
    su - postgres -c "psql -c \"CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}';\""
    su - postgres -c "psql -c \"CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};\""
    
    # Create .env file
    cat > "${CONFIG_DIR}/.env" << EOF
# Generated by password-vault installer
PROJECT_NAME=Password Vault
API_V1_STR=/api/v1

# Security
SECRET_KEY=$(openssl rand -hex 32)
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# PostgreSQL
POSTGRES_SERVER=localhost
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=${DB_NAME}

# CORS
BACKEND_CORS_ORIGINS=["http://localhost:3000"]
EOF
}

# Configure systemd service
setup_systemd() {
    log_info "Setting up systemd service..."
    cat > /etc/systemd/system/password-vault.service << EOF
[Unit]
Description=Password Vault Service
After=network.target postgresql.service

[Service]
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
WorkingDirectory=${INSTALL_DIR}
Environment=PATH=${PYTHON_VENV}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
EnvironmentFile=${CONFIG_DIR}/.env
ExecStart=${PYTHON_VENV}/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000
Restart=always

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable password-vault
}

# Initialize database schema
init_database() {
    log_info "Initializing database schema..."
    source "${PYTHON_VENV}/bin/activate"
    export PYTHONPATH="${INSTALL_DIR}"
    
    # Wait for PostgreSQL to be ready
    until su - postgres -c "psql -c '\l'" >/dev/null 2>&1; do
        log_info "Waiting for PostgreSQL to start..."
        sleep 1
    done
    
    # Run migrations
    cd "${INSTALL_DIR}"
    alembic upgrade head
}

# Set proper permissions
set_permissions() {
    log_info "Setting permissions..."
    chown -R "${SERVICE_USER}:${SERVICE_GROUP}" "${INSTALL_DIR}"
    chown -R "${SERVICE_USER}:${SERVICE_GROUP}" "${CONFIG_DIR}"
    chown -R "${SERVICE_USER}:${SERVICE_GROUP}" "${LOG_DIR}"
    chown -R "${SERVICE_USER}:${SERVICE_GROUP}" "${DATA_DIR}"
    
    chmod 750 "${INSTALL_DIR}"
    chmod 750 "${CONFIG_DIR}"
    chmod 750 "${LOG_DIR}"
    chmod 750 "${DATA_DIR}"
    chmod 600 "${CONFIG_DIR}/.env"
}

# Configure SELinux if enabled
setup_selinux() {
    if command -v selinuxenabled >/dev/null && selinuxenabled; then
        log_info "Configuring SELinux..."
        
        # Install SELinux tools if needed
        dnf install -y policycoreutils-python-utils
        
        # Set appropriate contexts
        semanage fcontext -a -t httpd_sys_content_t "${INSTALL_DIR}(/.*)?"
        semanage fcontext -a -t httpd_sys_rw_content_t "${LOG_DIR}(/.*)?"
        semanage fcontext -a -t httpd_sys_rw_content_t "${DATA_DIR}(/.*)?"
        restorecon -Rv "${INSTALL_DIR}" "${LOG_DIR}" "${DATA_DIR}"
        
        # Allow network connections
        setsebool -P httpd_can_network_connect on
    fi
}

# Main installation process
main() {
    log_info "Starting Password Vault installation..."
    
    create_directories
    create_service_user
    install_python_deps
    setup_database
    setup_systemd
    init_database
    set_permissions
    setup_selinux
    
    log_info "Installation completed successfully!"
    log_info "You can start the service with: systemctl start password-vault"
    
    # Save installation info
    log_info "Saving installation information..."
    cat > "${CONFIG_DIR}/install_info.txt" << EOF
Installation Date: $(date)
Database User: ${DB_USER}
Database Name: ${DB_NAME}
Service User: ${SERVICE_USER}
Install Directory: ${INSTALL_DIR}
Config Directory: ${CONFIG_DIR}
Log Directory: ${LOG_DIR}
Data Directory: ${DATA_DIR}
EOF
}

# Run main installation
main